### ISSUE TITLE
Plugin crashes on registering in background

### ISSUE THREAD

**Issue by sergey-triputsco** [MisterJimson/flutter_keyboard_visibility#32]
Hi.

When registering plugin in background next line causes a crash. As I understand it is redundant since `onAttachedToActivity` does listener registration and after removing it nothing will change.

https://github.com/MisterJimson/flutter_keyboard_visibility/blob/45262da8fde7af056b07b37ab16c1fbbf8062bbe/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java#L41

Stacktrace:
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
        at android.app.ActivityThread.access$1500(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
        at com.jrai.flutter_keyboard_visibility.FlutterKeyboardVisibilityPlugin.listenForKeyboard(FlutterKeyboardVisibilityPlugin.java:105)
        at com.jrai.flutter_keyboard_visibility.FlutterKeyboardVisibilityPlugin.registerWith(FlutterKeyboardVisibilityPlugin.java:41)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:53)`

**Comment by sergey-triputsco** [comment]
PR with a proposed fix #33

**Comment by MisterJimson** [comment]
Is your Android project migrated to the Flutter 1.12+ structure? https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Although #33 will fix the crash, backgrounding with plugins is much improved if you use the v2 of Android embedding. After this PR is merged, what happens when the app is brought to the foreground? Will the plugin even work if it never calls `plugin.listenForKeyboard`?

**Comment by bhanuka96** [comment]
waiting 2 months 😭 for solution
\

**Comment by MisterJimson** [comment]
I'm worried about the potential fix for #33, if you open the app after it was started in the background, won't the listener not gte created?

Not to mention you can fix this yourself by migrating to Flutter 1.12+ Android project structure: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by MisterJimson** [comment]
So reviewing the code https://github.com/flutter/plugins it seems the best way to fix this would be migrating your apps to the Flutter 1.12 Android project structure as linked above.

That is the only way the large majority of Flutter plugins can properly support backgrounding. The PR to null check the activity can introduce bugs when the UI is brought into the foreground.

Also version 3.0.0 won’t crash as commented above, but that is because the library wasn’t working at all on older Android projects.
